name: 'dbtproject'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths:
  - models
  - shared_dbt/Code/dbt/models

macro-paths:
  - macros
  - shared_dbt/Code/dbt/macros

seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
docs-paths: ["docs"]
asset-paths: ["assets"]